fixed naming

diff --git a/.github/workflows/check-mijn-amsterdam.yml b/.github/workflows/check-mijn-amsterdam.yml
--- a/.github/workflows/check-mijn-amsterdam.yml
+++ b/.github/workflows/check-mijn-amsterdam.yml
@@ -8,10 +8,13 @@ jobs:
   ssl-check:
     runs-on: ubuntu-latest
     steps:
+      - name: Create local cert directory
+        run: mkdir -p ./certs
+
       - name: Download DigiCert CA certificate
         run: |
-          mkdir -p /etc/ssl/certs
-          curl -o /etc/ssl/certs/DigiCertCA.crt https://dl.cacerts.digicert.com/DigiCertG2TLSEURSA4096SHA3842022CA1.crt
+          curl -o ./certs/DigiCertCA.crt https://dl.cacerts.digicert.com/DigiCertG2TLSEURSA4096SHA3842022CA1.crt
+
       - name: Test SSL with curl from GitHub Actions
         run: |
-          curl -vI --cacert /etc/ssl/certs/DigiCertCA.crt https://mijn.amsterdam.nl || echo "Connection failed"
+          curl -vI --cacert ./certs/DigiCertCA.crt https://mijn.amsterdam.nl || echo "Connection failed"
